name: Execute Easygenerator Scripts
on: workflow_dispatch
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command:
                npm run task-scripts-headless

      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome Test Report
          path: cypress/reports/html